/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(f15d7f28-e302-11ea-be21-43780523df9c), function]
interface nsIEditableSupportSetCompositionCallback : nsISupports
{
  void onSetComposition(in AString text);
};

[scriptable, uuid(f22a3d60-e302-11ea-8901-bf257d17b517), function]
interface nsIEditableSupportEndCompositionCallback : nsISupports
{
  void onEndComposition(in AString text);
};

[scriptable, uuid(e92d236c-e500-11ea-b121-e752c5a6ecc8), function]
interface nsIEditableSupportSendKeyCallback : nsISupports
{
  void onSendKey(in AString key);
};

[scriptable, uuid(f1ce658a-e500-11ea-bea1-6724d410da49), function]
interface nsIEditableSupportKeydownCallback : nsISupports
{
  void onKeydown(in AString key);
};

[scriptable, uuid(f7467dc2-e500-11ea-8789-cb53d8824320), function]
interface nsIEditableSupportKeyupCallback : nsISupports
{
  void onKeyup(in AString key);
};

[scriptable, uuid(821361d8-e4ff-11ea-89db-9f28f78da76a)]
interface nsIGeckoEditableSupportProxy : nsISupports
{
  void init();
  void handleFocus();
  void handleBlur();
  void attach(in nsISupports owner);
  void detach(in int32_t id);
  void setComposition(in nsISupports owner,
                      in nsIEditableSupportSetCompositionCallback callback);
  void endComposition(in nsISupports owner,
                      in nsIEditableSupportEndCompositionCallback callback);
  void sendKey(in nsISupports owner,
               in nsIEditableSupportSendKeyCallback callback);
  void keydown(in nsISupports owner,
               in nsIEditableSupportKeydownCallback callback);
  void keyup(in nsISupports owner,
             in nsIEditableSupportKeyupCallback callback);
};
