/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(62858594-dbff-48ae-ba4b-8aecc71bedfe), function]
interface nsIInputMethodSetCompositionCallback : nsISupports
{
  [implicit_jscontext]
  void onSetComposition(in nsresult status, in jsval result);
};

[scriptable, uuid(a9e5bbf7-9097-4710-aac9-33f36378b1ec), function]
interface nsIInputMethodEndCompositionCallback : nsISupports
{
  [implicit_jscontext]
  void onEndComposition(in nsresult status, in jsval result);
};

[scriptable, uuid(ff963d00-e500-11ea-9bbc-e7e090b18d30), function]
interface nsIInputMethodSendKeyCallback : nsISupports
{
  [implicit_jscontext]
  void onSendKey(in nsresult status, in jsval result);
};

[scriptable, uuid(054ca34c-e501-11ea-93b7-8b01d748a84c), function]
interface nsIInputMethodKeydownCallback : nsISupports
{
  [implicit_jscontext]
  void onKeydown(in nsresult status, in jsval result);
};

[scriptable, uuid(0aefbadc-e501-11ea-8411-b73fef287066), function]
interface nsIInputMethodKeyupCallback : nsISupports
{
  [implicit_jscontext]
  void onKeyup(in nsresult status, in jsval result);
};

[scriptable, uuid(960e39b0-e4ff-11ea-8c0e-b7c5f54cec64)]
interface nsIInputMethodProxy : nsISupports
{
  void init();
  void attach(in nsISupports owner);
  void detach(in int32_t id);
  void setComposition(in nsISupports owner, in AString text,
                      in nsIInputMethodSetCompositionCallback callback);
  void endComposition(in nsISupports owner, in AString text,
                      in nsIInputMethodEndCompositionCallback callback);
  void sendKey(in nsISupports owner, in AString key,
                      in nsIInputMethodSendKeyCallback callback);
  void keydown(in nsISupports owner, in AString key,
                      in nsIInputMethodKeydownCallback callback);
  void keyup(in nsISupports owner, in AString key,
                      in nsIInputMethodKeyupCallback callback);
};
