/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "nsIWifiElement.idl"

interface nsIScanResult;

[scriptable, uuid(3489f412-1b19-4c6f-8cf2-703ac5c2aed8)]
interface nsIWifiResult : nsISupports
{
  /** Status code */
  const unsigned long SUCCESS = 0;
  const unsigned long ERROR_COMMAND_FAILED = 1;
  const unsigned long ERROR_INVALID_INTERFACE = 2;
  const unsigned long ERROR_INVALID_ARGS = 3;
  const unsigned long ERROR_NOT_SUPPORTED = 4;
  const unsigned long ERROR_TIMEOUT = 5;
  const unsigned long ERROR_UNKNOWN = 6;

  readonly attribute unsigned long id;
  readonly attribute unsigned long status;

  readonly attribute AString driverVersion;
  readonly attribute AString firmwareVersion;
  readonly attribute AString macAddress;
  readonly attribute AString staInterface;
  readonly attribute AString apInterface;
  readonly attribute unsigned long capabilities;
  readonly attribute unsigned long staCapabilities;
  readonly attribute unsigned long debugLevel;
  readonly attribute unsigned long numStations;

  /** Station link layer statistics */
  readonly attribute nsILinkLayerStats linkLayerStats;

  /**
   * Query supported channel list
   *
   * Invoke the function to get the return value for GET_CHANNELS_FOR_BAND.
   */
  Array<int32_t> getChannels();
  /**
   * Query signal information from current connected access point
   *
   * Invoke the function to get the return value for SIGNAL_POLL.
   */
  Array<int32_t> signalPoll();
  /**
   * Query single scan results
   *
   * Invoke the function to get the return value for GET_SCAN_RESULTS.
   */
  Array<nsIScanResult> getScanResults();
};
