/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "nsIWifiElement.idl"

interface nsIStateChanged;

[scriptable, uuid(3f97bbaf-ec6f-4cc4-a9b0-f6e67aa78dc4)]
interface nsIWifiEvent : nsISupports
{
  readonly attribute AString name;
  readonly attribute AString bssid;
  readonly attribute boolean locallyGenerated;
  readonly attribute unsigned long reason;
  readonly attribute nsIStateChanged stateChanged;
};
