/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsIAnqpResponse.idl"
#include "nsISupports.idl"
#include "nsIWifiElement.idl"

interface nsIStateChanged;

[scriptable, uuid(3f97bbaf-ec6f-4cc4-a9b0-f6e67aa78dc4)]
interface nsIWifiEvent : nsISupports
{
  /** Connection failure reason code */
  const uint32_t AUTH_FAILURE_UNKNOWN = 0;
  const uint32_t AUTH_FAILURE_NONE = 1;
  const uint32_t AUTH_FAILURE_TIMEOUT = 2;
  const uint32_t AUTH_FAILURE_WRONG_KEY = 3;
  const uint32_t AUTH_FAILURE_EAP_FAILURE = 4;

  /** Error code for EAP or EAP Method as per RFC-4186 10.18 */
  const uint32_t ERROR_CODE_NONE = -1;
  const uint32_t ERROR_EAP_SIM_GENERAL_FAILURE_AFTER_AUTH = 0;
  const uint32_t ERROR_EAP_SIM_TEMPORARILY_DENIED = 1026;
  const uint32_t ERROR_EAP_SIM_NOT_SUBSCRIBED = 1031;
  const uint32_t ERROR_EAP_SIM_GENERAL_FAILURE_BEFORE_AUTH = 16384;
  const uint32_t ERROR_EAP_SIM_VENDOR_SPECIFIC_EXPIRED_CERT = 16385;

  /**
   * Number of the event sent from hal.
   */
  readonly attribute AString name;

  /**
   * Use for event that contains network BSSID.
   */
  readonly attribute AString bssid;

  /**
   * Use for onDisconnected event to indicate if the disconnection is
   * triggered locally.
   */
  readonly attribute boolean locallyGenerated;

  /**
   * Contain the reason code from supplicant, or the authentication failure
   * defined in this idl.
   *
   * Possible values: AUTH_FAILURE_*.
   */
  readonly attribute uint32_t reason;

  /**
   * 802.11 code to indicate the association reject reason.
   * Refer to section 8.4.1.9 of IEEE 802.11 spec.
   */
  readonly attribute uint32_t statusCode;

  /**
   * Indicate the number of connected clients on hotspot.
   * Refer to onNumAssociatedStationsChanged event.
   */
  readonly attribute uint32_t numStations;

  /**
   * Error code for EAP or EAP Method.
   * Possible values: ERROR_EAP_SIM_*.
   */
  readonly attribute int32_t errorCode;

  /**
   * Whether failure is due to timeout rather response from the AP.
   * Refer to onAssociationRejected.
   */
  readonly attribute boolean timeout;

  /**
   * Indicate supplicant state change event.
   */
  readonly attribute nsIStateChanged stateChanged;

  /**
   * Use for onNetworkEapSimUmtsAuthRequest event to get UMTS authentication
   * parameters. (Refer RFC 4187)
   */
  readonly attribute AString rand;

  readonly attribute AString autn;

  /**
   * ANQP network key to identify the AP that contain the same ANQP information.
   */
  readonly attribute AString anqpNetworkKey;

  /**
   * Contains ANQP data received from access point.
   */
  readonly attribute nsIAnqpResponse anqpResponse;

  /**
   * WPS Configuration Error.
   */
  readonly attribute uint16_t wpsConfigError;

  /**
   * Vendor specific Error Indication for WPS event messages.
   */
  readonly attribute uint16_t wpsErrorIndication;

  /**
   * Use for onNetworkEapSimGsmAuthRequest event to get GSM authentication
   * parameters. (Refer RFC 4186)
   */
  Array<AString> getGsmRands();
};
