/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsIMobileCellInfo;
interface nsIMobileNetworkInfo;

[scriptable, uuid(572a6ad4-d147-4095-8111-41de10add6d1)]
interface nsIMobileConnectionInfo : nsISupports
{
  /**
   * State of the connection.
   *
   * Possible values: 'notSearching', 'searching', 'denied', 'registered' or
   *                  null (unknown).
   */
  readonly attribute AString state;

  /**
   * Indicates whether the connection is ready.
   *
   * Note: The meaning of "connection ready" for data and voice are different.
   *       - Data: the "default" data connection is established or not.
   *       - Voice: voice is registered to network or not.
   */
  readonly attribute bool connected;

  /**
   * Indicates whether only emergency calls are possible.
   *
   * This flag is only relevant to voice connections and when 'connected' is
   * false.
   */
  readonly attribute bool emergencyCallsOnly;

  /**
   * Indicates whether the connection is going through a foreign operator
   * (roaming) or not.
   */
  readonly attribute bool roaming;

  /**
   * Network operator information.
   */
  readonly attribute nsIMobileNetworkInfo network;

  /**
   * Type of connection.
   *
   * Possible values: 'gsm', 'gprs', 'edge', 'umts', 'hsdpa', 'hsupa', 'hspa',
   *                  'hspa+', 'is95a', 'is95b', '1xrtt', 'evdo0', 'evdoa',
   *                  'evdob', 'ehrpd', 'lte' , 'iwlan' or null (unknown).
   */
  readonly attribute AString type;

  /**
   * Cell location information.
   */
  readonly attribute nsIMobileCellInfo cell;


  /**
   * Reason Data Denied.
   *
   * if state is 'denied' this is an enumerated reason why
   * registration was denied. See 3GPP TS 24.008,
   * Annex G.6 "Additional cause codes for GMM".
   * 7 == GPRS services not allowed
   * 8 == GPRS services and non-GPRS services not allowed
   * 9 == MS identity cannot be derived by the network
   * 10 == Implicitly detached
   * 14 == GPRS services not allowed in this PLMN
   * 16 == MSC temporarily not reachable
   * 40 == No PDP context activated
  */

  readonly attribute long reasonDataDenied;
};
