/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(500b7a15-e52e-4394-9aa3-fcfa23c78219)]
interface nsIPCOService : nsISupports
{
  void updatePcoData(in Array<jsval> contents);

  /**
   * Get the restrict status.
   *
   * @param origin
   *        Follow the origin to check the restrict status.
   */
  boolean getRestriction(in AString origin);
};