/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(46859c88-9946-4d63-a0e3-72b0f3e1da14)]
interface nsIPCOService : nsISupports
{
  void updatePcoData([optional] in unsigned long count,
                     [array, size_is(count), retval] in jsval pcoValue);

  /**
   * Get the restrict status.
   *
   * @param aAppId
   *        Follow the app id to check the restrict status.
   */
  boolean getRestriction([optional] in long aAppId);
};