#include "nsISupports.idl"

[scriptable, uuid(8ccccd66-f5cb-11eb-b929-0300f8af1601)]
interface nsIRemoteWorkerActorSelector : nsISupports
{
  /**
   * Get a suggested content process for service worker to spawn at.
   * aScope: Scope of service worker which will be spawned.
   */
  int32_t getSuggestedPid(in ACString aScope);
};
