/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "nsIWifiElement.idl"

interface nsIScanResult;

[scriptable, uuid(86d6ca17-5e9c-4939-a2ca-275d08c117ef)]
interface nsIWifiResult : nsISupports
{
  readonly attribute unsigned long id;
  readonly attribute boolean status;

  readonly attribute AString driverVersion;
  readonly attribute AString firmwareVersion;
  readonly attribute AString macAddress;
  readonly attribute AString staInterface;
  readonly attribute AString apInterface;
  readonly attribute unsigned long capabilities;
  readonly attribute unsigned long staCapabilities;
  readonly attribute unsigned long debugLevel;

  Array<int32_t> getChannels();

  void getScanResults([optional] out unsigned long count,
                      [array, size_is(count), retval] out nsIScanResult scanResults);
};
