/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "nsIWifiElement.idl"

interface nsIScanResult;

[scriptable, uuid(10843bf3-d067-4787-860a-2da92bb565e1)]
interface nsIWifiResult : nsISupports
{
  readonly attribute unsigned long id;
  readonly attribute boolean status;

  readonly attribute AString driverVersion;
  readonly attribute AString firmwareVersion;
  readonly attribute AString macAddress;
  readonly attribute AString staInterface;
  readonly attribute AString apInterface;
  readonly attribute unsigned long capabilities;
  readonly attribute unsigned long staCapabilities;
  readonly attribute unsigned long debugLevel;
  void getScanResults([optional] out unsigned long count,
                      [array, size_is(count), retval] out nsIScanResult scanResults);
};
